name: stats

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "run"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: luebken/awesome-crossplane-providers
      - name: Echo
        run: echo Hello, world!
      - name: Docker Pull
        run: docker pull luebken/awesome-crossplane-providers:latest
      - name: Docker run
        run: docker run luebken/awesome-crossplane-providers:latest
