# Creates the provider stats for all known providers
name: provider-stats
on:
  # Manually from the Actions tab
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - name: go-run
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          go run ./cmd/axpp/main.go provider-names
