name: provider-stats
on:
  # Manually from the Actions tab
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - name: run
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          go run ./cmd/axpp/main.go provider-stats
      - name: git diff
        run: git diff
      - name: Commit Stats
        run: |
          git config --global user.name 'Gitub Action'
          git config --global user.email 'Gitub-Action@users.noreply.github.com'
          git add .
          git commit -am "Daily Stats Update"
          git push