# Creates the provider stats for all known providers
name: provider-stats

on:
  # Daily
  schedule:
    - cron: "59 23 * * *"
  # Manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - name: Docker Pull
        run: docker pull luebken/awesome-crossplane-providers:latest
      - name: Docker run provider-stats
        run: docker run -v $GITHUB_WORKSPACE:/repo --env MY_GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }} luebken/awesome-crossplane-providers:latest
      - name: build site
        run: |
          cd site
          npm install
          npm run build
          cd ..
          rm -rf docs/*
          cp -r site/build/. docs/
      - name: git diff
        run: git diff
      - name: Commit stats
        run: |
          git config --global user.name 'Gitub Action'
          git config --global user.email 'Gitub-Action@users.noreply.github.com'
          git add .
          git commit -am "Daily Stats Update"
          git push
